import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.csprng import generate_random_bytes

def test_key_uniqueness():
    """Test that generated keys are unique"""
    key_set = set()
    num_keys = 1000
    
    print(f"Generating {num_keys} random keys...")
    
    for i in range(num_keys):
        key = generate_random_bytes(16)
        key_hex = key.hex()
        
        if key_hex in key_set:
            raise AssertionError(f"Duplicate key found: {key_hex}")
        
        key_set.add(key_hex)
        
        if (i + 1) % 100 == 0:
            print(f"Generated {i + 1} unique keys...")
    
    print(f"Successfully generated {len(key_set)} unique keys.")

def test_basic_entropy():
    """Test basic entropy properties of generated bytes"""
    print("Testing entropy of generated bytes...")
    
    data = generate_random_bytes(10000)
    
    total_bits = len(data) * 8
    ones_count = sum(bin(byte).count('1') for byte in data)
    ones_ratio = ones_count / total_bits
    
    print(f"Total bits: {total_bits}")
    print(f"Ones count: {ones_count}")
    print(f"Ones ratio: {ones_ratio:.4f} (should be close to 0.5)")
    
    assert 0.45 <= ones_ratio <= 0.55, f"Unexpected ones ratio: {ones_ratio}"
    print("Entropy test passed")

def test_nist_preparation():
    """Generate a large random file for NIST testing"""
    print("Generating data for NIST testing...")
    
    total_size = 10_000_000  
    output_file = 'nist_test_data.bin'
    
    with open(output_file, 'wb') as f:
        bytes_written = 0
        chunk_size = 4096
        
        while bytes_written < total_size:
            chunk = generate_random_bytes(min(chunk_size, total_size - bytes_written))
            f.write(chunk)
            bytes_written += len(chunk)
    
    print(f"Generated {bytes_written} bytes for NIST testing in '{output_file}'")

if __name__ == "__main__":
    print("Running CSPRNG tests...")
    print()
    
    test_key_uniqueness()
    print()
    
    test_basic_entropy()
    print()
    
    test_nist_preparation()
    print()
    
    print("All tests completed successfully!")